# DB is created with the commando "docker compose up -d"
services:
  frontend:
    image: ml_frontend # This needs to be built from the other repo first
    container_name: ml_frontend
    environment:
      BACKEND_URL: http://ml_backend:5000
      BACKEND_URL_HOST: ml_backend:5000
    ports:
      - "8080:80"
    depends_on:
      - backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: ml_backend
    container_name: ml_backend
    environment:
      APP_ENV: development
      ML_DB_URL: postgresql://mluser:mlpass@db:5432/mlregistry
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: postgres:16
    container_name: ml_postgres
    environment:
      POSTGRES_USER: mluser
      POSTGRES_PASSWORD: mlpass
      POSTGRES_DB: mlregistry
    ports:
      - "5432:5432" # Specifies the port the container will run on
    volumes:
      # This maps the local init folder to the container init path
      - ./db/init:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: # Persist data even if the container is deleted
